### ISSUE TITLE
What are profiles

### ISSUE THREAD

**Issue by abishekrsrikaanth** [omaralalwi/laravel-taxify#14]
Can you please elaborate a bit on what are profiles, its purpose and how to create them to use it with this package?

**Comment by omaralalwi** [comment]
the profiles are tax settings .
every p profile define a group of tax settings to allow you use more than
one of tax .
for example you have a tax percentage for electronics products .
and another tax for food products .

you must create electronics profile to implement with electronics products
and food_tax profile to implement with foods products.

please see docs for more
https://omaralalwi.github.io/laravel-taxify/#/?id=laravel-taxify
